In [1]:
import pandas as pd
import requests

In [2]:
response = requests.get("https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=100&page=1")

In [3]:
response.json()

[{'id': 'bitcoin',
  'symbol': 'btc',
  'name': 'Bitcoin',
  'image': 'https://coin-images.coingecko.com/coins/images/1/large/bitcoin.png?1696501400',
  'current_price': 76507,
  'market_cap': 1533277467419,
  'market_cap_rank': 1,
  'fully_diluted_valuation': 1533277467419,
  'total_volume': 33285343616,
  'high_24h': 78226,
  'low_24h': 76595,
  'price_change_24h': -1093.6609136584157,
  'price_change_percentage_24h': -1.40934,
  'market_cap_change_24h': -20518213338.1333,
  'market_cap_change_percentage_24h': -1.32052,
  'circulating_supply': 20021793.0,
  'total_supply': 20021793.0,
  'max_supply': 21000000.0,
  'ath': 126080,
  'ath_change_percentage': -39.31837,
  'ath_date': '2025-10-06T18:57:42.558Z',
  'atl': 67.81,
  'atl_change_percentage': 112727.69737,
  'atl_date': '2013-07-06T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-04-28T07:17:21.934Z'},
 {'id': 'ethereum',
  'symbol': 'eth',
  'name': 'Ethereum',
  'image': 'https://coin-images.coingecko.com/coins/images/279/large/ethereum.png?1696501628',
  'current_price': 2272.82,
  'market_cap': 274506054614,
  'market_cap_rank': 2,
  'fully_diluted_valuation': 274506054614,
  'total_volume': 14492067695,
  'high_24h': 2327.9,
  'low_24h': 2271.74,
  'price_change_24h': -44.488366251451225,
  'price_change_percentage_24h': -1.91983,
  'market_cap_change_24h': -5440238940.096649,
  'market_cap_change_percentage_24h': -1.94332,
  'circulating_supply': 120688270.8382775,
  'total_supply': 120688270.8382775,
  'max_supply': None,
  'ath': 4946.05,
  'ath_change_percentage': -54.04781,
  'ath_date': '2025-08-24T19:21:03.333Z',
  'atl': 0.432979,
  'atl_change_percentage': 524825.77274,
  'atl_date': '2015-10-20T00:00:00.000Z',
  'roi': {'times': 38.719633322207436,
   'currency': 'btc',
   'percentage': 3871.9633322207437},
  'last_updated': '2026-04-28T07:17:22.269Z'},
 {'id': 'tether',
  'symbol': 'usdt',
  'name': 'Tether',
  'image': 'https://coin-images.coingecko.com/coins/images/325/large/Tether.png?1696501661',
  'current_price': 0.999885,
  'market_cap': 189712695305,
  'market_cap_rank': 3,
  'fully_diluted_valuation': 195179052274,
  'total_volume': 57128572123,
  'high_24h': 1.0,
  'low_24h': 0.999852,
  'price_change_24h': -0.000199732819281762,
  'price_change_percentage_24h': -0.01997,
  'market_cap_change_24h': -70574279.34725952,
  'market_cap_change_percentage_24h': -0.03719,
  'circulating_supply': 189732931140.392,
  'total_supply': 195199871181.9162,
  'max_supply': None,
  'ath': 1.32,
  'ath_change_percentage': -24.42851,
  'ath_date': '2018-07-24T00:00:00.000Z',
  'atl': 0.572521,
  'atl_change_percentage': 74.64562,
  'atl_date': '2015-03-02T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-04-28T07:17:22.834Z'},
 {'id': 'ripple',
  'symbol': 'xrp',
  'name': 'XRP',
  'image': 'https://coin-images.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png?1696501442',
  'current_price': 1.39,
  'market_cap': 85599699229,
  'market_cap_rank': 4,
  'fully_diluted_valuation': 138749315633,
  'total_volume': 1838960230,
  'high_24h': 1.42,
  'low_24h': 1.39,
  'price_change_24h': -0.030533531036151418,
  'price_change_percentage_24h': -2.15565,
  'market_cap_change_24h': -1756045068.4763184,
  'market_cap_change_percentage_24h': -2.01022,
  'circulating_supply': 61684942428.0,
  'total_supply': 99985673125.0,
  'max_supply': 100000000000.0,
  'ath': 3.65,
  'ath_change_percentage': -61.99215,
  'ath_date': '2025-07-18T03:40:53.808Z',
  'atl': 0.00268621,
  'atl_change_percentage': 51493.57351,
  'atl_date': '2014-05-22T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-04-28T07:17:23.622Z'},
 {'id': 'binancecoin',
  'symbol': 'bnb',
  'name': 'BNB',
  'image': 'https://coin-images.coingecko.com/coins/images/825/large/bnb-icon2_2x.png?1696501970',
  'current_price': 622.35,
  'market_cap': 83931297076,
  'market_cap_rank': 5,
  'fully_diluted_valuation': 83931297076,
  'total_volume': 868015184,
  'high_24h': 628.8,
  'low_24h': 619.7,
  'price_change_24h': -3.577603144126897,
  'price_change_percentage_24h': -0.57157,
  'market_cap_change_24h': -565057939.4632568,
  'market_cap_change_percentage_24h': -0.66874,
  'circulating_supply': 134786231.69,
  'total_supply': 134786231.69,
  'max_supply': 200000000.0,
  'ath': 1369.99,
  'ath_change_percentage': -54.57279,
  'ath_date': '2025-10-13T08:41:24.131Z',
  'atl': 0.0398177,
  'atl_change_percentage': 1562895.80992,
  'atl_date': '2017-10-19T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-04-28T07:17:25.866Z'},
 {'id': 'usd-coin',
  'symbol': 'usdc',
  'name': 'USDC',
  'image': 'https://coin-images.coingecko.com/coins/images/6319/large/USDC.png?1769615602',
  'current_price': 0.999781,
  'market_cap': 77587617226,
  'market_cap_rank': 6,
  'fully_diluted_valuation': 77599268780,
  'total_volume': 12899372823,
  'high_24h': 1.0,
  'low_24h': 0.99965,
  'price_change_24h': -7.2077906629886e-05,
  'price_change_percentage_24h': -0.00721,
  'market_cap_change_24h': -168430315.4543457,
  'market_cap_change_percentage_24h': -0.21661,
  'circulating_supply': 77600570363.33447,
  'total_supply': 77612223862.19577,
  'max_supply': None,
  'ath': 1.043,
  'ath_change_percentage': -4.17855,
  'ath_date': '2018-11-15T00:00:00.000Z',
  'atl': 0.877647,
  'atl_change_percentage': 13.92545,
  'atl_date': '2023-03-11T08:02:13.981Z',
  'roi': None,
  'last_updated': '2026-04-28T07:17:24.961Z'},
 {'id': 'solana',
  'symbol': 'sol',
  'name': 'Solana',
  'image': 'https://coin-images.coingecko.com/coins/images/4128/large/solana.png?1718769756',
  'current_price': 83.75,
  'market_cap': 48295107227,
  'market_cap_rank': 7,
  'fully_diluted_valuation': 52432130926,
  'total_volume': 3227683546,
  'high_24h': 85.72,
  'low_24h': 83.8,
  'price_change_24h': -1.8594882242136919,
  'price_change_percentage_24h': -2.17213,
  'market_cap_change_24h': -995202504.0906372,
  'market_cap_change_percentage_24h': -2.01906,
  'circulating_supply': 575970250.6192409,
  'total_supply': 625308635.2668556,
  'max_supply': None,
  'ath': 293.31,
  'ath_change_percentage': -71.44768,
  'ath_date': '2025-01-19T11:15:27.957Z',
  'atl': 0.500801,
  'atl_change_percentage': 16622.67468,
  'atl_date': '2020-05-11T19:35:23.449Z',
  'roi': None,
  'last_updated': '2026-04-28T07:17:28.051Z'},
 {'id': 'tron',
  'symbol': 'trx',
  'name': 'TRON',
  'image': 'https://coin-images.coingecko.com/coins/images/1094/large/photo_2026-04-13_09-59-16.png?1776048311',
  'current_price': 0.323583,
  'market_cap': 30664298422,
  'market_cap_rank': 8,
  'fully_diluted_valuation': 30664636863,
  'total_volume': 464801807,
  'high_24h': 0.326281,
  'low_24h': 0.323241,
  'price_change_24h': -8.5873502599421e-05,
  'price_change_percentage_24h': -0.02653,
  'market_cap_change_24h': -12357182.006458282,
  'market_cap_change_percentage_24h': -0.04028,
  'circulating_supply': 94783841775.44359,
  'total_supply': 94784887899.6417,
  'max_supply': None,
  'ath': 0.431288,
  'ath_change_percentage': -24.973,
  'ath_date': '2024-12-04T00:10:40.323Z',
  'atl': 0.00180434,
  'atl_change_percentage': 17833.56072,
  'atl_date': '2017-11-12T00:00:00.000Z',
  'roi': {'times': 169.3066856059279,
   'currency': 'usd',
   'percentage': 16930.66856059279},
  'last_updated': '2026-04-28T07:17:21.030Z'},
 {'id': 'figure-heloc',
  'symbol': 'figr_heloc',
  'name': 'Figure Heloc',
  'image': 'https://coin-images.coingecko.com/coins/images/68480/large/figure.png?1755863954',
  'current_price': 1.031,
  'market_cap': 17627082991,
  'market_cap_rank': 9,
  'fully_diluted_valuation': 17627082991,
  'total_volume': 23762894,
  'high_24h': 1.04,
  'low_24h': 1.018,
  'price_change_24h': 0.0125866,
  'price_change_percentage_24h': 1.23637,
  'market_cap_change_24h': 212303011,
  'market_cap_change_percentage_24h': 1.2191,
  'circulating_supply': 17103440631.897,
  'total_supply': 17103440631.897,
  'max_supply': None,
  'ath': 1.049,
  'ath_change_percentage': -1.76361,
  'ath_date': '2026-03-09T17:00:25.937Z',
  'atl': 0.155357,
  'atl_change_percentage': 563.38746,
  'atl_date': '2025-10-31T14:27:24.456Z',
  'roi': None,
  'last_updated': '2026-04-28T05:19:04.883Z'},
 {'id': 'dogecoin',
  'symbol': 'doge',
  'name': 'Dogecoin',
  'image': 'https://coin-images.coingecko.com/coins/images/5/large/dogecoin.png?1696501409',
  'current_price': 0.099213,
  'market_cap': 15304339049,
  'market_cap_rank': 10,
  'fully_diluted_valuation': 15304379791,
  'total_volume': 1657751337,
  'high_24h': 0.10032,
  'low_24h': 0.097136,
  'price_change_24h': 0.00136026,
  'price_change_percentage_24h': 1.39011,
  'market_cap_change_24h': 242077510,
  'market_cap_change_percentage_24h': 1.60718,
  'circulating_supply': 154013106383.7052,
  'total_supply': 154013516383.7052,
  'max_supply': None,
  'ath': 0.731578,
  'ath_change_percentage': -86.4385,
  'ath_date': '2021-05-08T05:08:23.458Z',
  'atl': 8.69e-05,
  'atl_change_percentage': 114064.18469,
  'atl_date': '2015-05-06T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-04-28T07:17:23.534Z'},
 {'id': 'whitebit',
  'symbol': 'wbt',
  'name': 'WhiteBIT Coin',
  'image': 'https://coin-images.coingecko.com/coins/images/27045/large/wbt_token.png?1696526096',
  'current_price': 54.08,
  'market_cap': 11551598961,
  'market_cap_rank': 11,
  'fully_diluted_valuation': 17295704900,
  'total_volume': 75831070,
  'high_24h': 55.17,
  'low_24h': 54.1,
  'price_change_24h': -0.7255833758535815,
  'price_change_percentage_24h': -1.32401,
  'market_cap_change_24h': -143967340.59454727,
  'market_cap_change_percentage_24h': -1.23096,
  'circulating_supply': 213418274.0,
  'total_supply': 319541866.0,
  'max_supply': 400000000.0,
  'ath': 64.11,
  'ath_change_percentage': -15.52184,
  'ath_date': '2025-12-10T20:16:13.582Z',
  'atl': 3.06,
  'atl_change_percentage': 1668.80353,
  'atl_date': '2023-02-13T19:01:21.899Z',
  'roi': None,
  'last_updated': '2026-04-28T07:17:22.410Z'},
 {'id': 'usds',
  'symbol': 'usds',
  'name': 'USDS',
  'image': 'https://coin-images.coingecko.com/coins/images/39926/large/usds.webp?1726666683',
  'current_price': 0.999622,
  'market_cap': 11028261667,
  'market_cap_rank': 12,
  'fully_diluted_valuation': 11028261667,
  'total_volume': 27852351,
  'high_24h': 0.999888,
  'low_24h': 0.998962,
  'price_change_24h': -1.130789653836e-05,
  'price_change_percentage_24h': -0.00113,
  'market_cap_change_24h': 3207223,
  'market_cap_change_percentage_24h': 0.02909,
  'circulating_supply': 11032116180.39268,
  'total_supply': 11032116180.39268,
  'max_supply': None,
  'ath': 1.15,
  'ath_change_percentage': -13.22229,
  'ath_date': '2026-04-02T07:21:14.655Z',
  'atl': 0.948265,
  'atl_change_percentage': 5.43002,
  'atl_date': '2024-10-03T13:19:28.826Z',
  'roi': None,
  'last_updated': '2026-04-28T07:17:23.166Z'},
 {'id': 'hyperliquid',
  'symbol': 'hype',
  'name': 'Hyperliquid',
  'image': 'https://coin-images.coingecko.com/coins/images/50882/large/hyperliquid.jpg?1729431300',
  'current_price': 40.36,
  'market_cap': 9632856308,
  'market_cap_rank': 13,
  'fully_diluted_valuation': 38884305490,
  'total_volume': 254843557,
  'high_24h': 42.85,
  'low_24h': 40.4,
  'price_change_24h': -2.071894328542477,
  'price_change_percentage_24h': -4.88271,
  'market_cap_change_24h': -507796357.0987053,
  'market_cap_change_percentage_24h': -5.00753,
  'circulating_supply': 238385315.9541414,
  'total_supply': 962274028.9541414,
  'max_supply': 1000000000.0,
  'ath': 59.3,
  'ath_change_percentage': -31.94118,
  'ath_date': '2025-09-18T03:30:30.650Z',
  'atl': 3.81,
  'atl_change_percentage': 959.70382,
  'atl_date': '2024-11-29T09:30:30.871Z',
  'roi': None,
  'last_updated': '2026-04-28T07:17:23.867Z'},
 {'id': 'leo-token',
  'symbol': 'leo',
  'name': 'LEO Token',
  'image': 'https://coin-images.coingecko.com/coins/images/8418/large/leo-token.png?1696508607',
  'current_price': 10.37,
  'market_cap': 9543773066,
  'market_cap_rank': 14,
  'fully_diluted_valuation': 10212337672,
  'total_volume': 289242,
  'high_24h': 10.45,
  'low_24h': 10.28,
  'price_change_24h': -0.00612883933804298,
  'price_change_percentage_24h': -0.05909,
  'market_cap_change_24h': -5755654.706243515,
  'market_cap_change_percentage_24h': -0.06027,
  'circulating_supply': 920739456.9,
  'total_supply': 985239504.0,
  'max_supply': None,
  'ath': 10.45,
  'ath_change_percentage': -0.83292,
  'ath_date': '2026-04-27T12:40:34.526Z',
  'atl': 0.799859,
  'atl_change_percentage': 1195.83614,
  'atl_date': '2019-12-24T15:14:35.376Z',
  'roi': None,
  'last_updated': '2026-04-28T07:17:25.504Z'},
 {'id': 'cardano',
  'symbol': 'ada',
  'name': 'Cardano',
  'image': 'https://coin-images.coingecko.com/coins/images/975/large/cardano.png?1696502090',
  'current_price': 0.245654,
  'market_cap': 9094752847,
  'market_cap_rank': 15,
  'fully_diluted_valuation': 11070727527,
  'total_volume': 304333018,
  'high_24h': 0.248384,
  'low_24h': 0.244056,
  'price_change_24h': -0.00176404107304845,
  'price_change_percentage_24h': -0.71298,
  'market_cap_change_24h': -55057760.93251991,
  'market_cap_change_percentage_24h': -0.60174,
  'circulating_supply': 36968110460.71545,
  'total_supply': 45000000000.0,
  'max_supply': 45000000000.0,
  'ath': 3.09,
  'ath_change_percentage': -92.04208,
  'ath_date': '2021-09-02T06:00:10.474Z',
  'atl': 0.01925275,
  'atl_change_percentage': 1175.94213,
  'atl_date': '2020-03-13T02:22:55.044Z',
  'roi': None,
  'last_updated': '2026-04-28T07:17:25.823Z'},
 {'id': 'bitcoin-cash',
  'symbol': 'bch',
  'name': 'Bitcoin Cash',
  'image': 'https://coin-images.coingecko.com/coins/images/780/large/bitcoin-cash-circle.png?1696501932',
  'current_price': 445.4,
  'market_cap': 8921769355,
  'market_cap_rank': 16,
  'fully_diluted_valuation': 8921769355,
  'total_volume': 154371947,
  'high_24h': 454.72,
  'low_24h': 445.48,
  'price_change_24h': -1.8860053456034507,
  'price_change_percentage_24h': -0.42165,
  'market_cap_change_24h': -40078794.47054291,
  'market_cap_change_percentage_24h': -0.44722,
  'circulating_supply': 20027153.02165078,
  'total_supply': 20027153.02165078,
  'max_supply': 21000000.0,
  'ath': 3785.82,
  'ath_change_percentage': -88.23491,
  'ath_date': '2017-12-20T00:00:00.000Z',
  'atl': 76.93,
  'atl_change_percentage': 478.93824,
  'atl_date': '2018-12-16T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-04-28T07:17:25.596Z'},
 {'id': 'monero',
  'symbol': 'xmr',
  'name': 'Monero',
  'image': 'https://coin-images.coingecko.com/coins/images/69/large/monero_logo.png?1696501460',
  'current_price': 375.97,
  'market_cap': 6938313592,
  'market_cap_rank': 17,
  'fully_diluted_valuation': 6938313592,
  'total_volume': 133435303,
  'high_24h': 393.76,
  'low_24h': 374.36,
  'price_change_24h': -8.182567785121648,
  'price_change_percentage_24h': -2.13005,
  'market_cap_change_24h': -143504099.6054535,
  'market_cap_change_percentage_24h': -2.02637,
  'circulating_supply': 18446744.07370955,
  'total_supply': 18446744.07370955,
  'max_supply': None,
  'ath': 797.73,
  'ath_change_percentage': -52.87076,
  'ath_date': '2026-01-14T19:34:07.049Z',
  'atl': 0.216177,
  'atl_change_percentage': 173816.25178,
  'atl_date': '2015-01-14T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-04-28T07:17:27.721Z'},
 {'id': 'chainlink',
  'symbol': 'link',
  'name': 'Chainlink',
  'image': 'https://coin-images.coingecko.com/coins/images/877/large/Chainlink_Logo_500.png?1760023405',
  'current_price': 9.22,
  'market_cap': 6709773085,
  'market_cap_rank': 18,
  'fully_diluted_valuation': 9228130047,
  'total_volume': 205837893,
  'high_24h': 9.35,
  'low_24h': 9.17,
  'price_change_24h': -0.09934250607191863,
  'price_change_percentage_24h': -1.06581,
  'market_cap_change_24h': -67116099.49114323,
  'market_cap_change_percentage_24h': -0.99037,
  'circulating_supply': 727099970.4523476,
  'total_supply': 1000000000.0,
  'max_supply': 1000000000.0,
  'ath': 52.7,
  'ath_change_percentage': -82.50076,
  'ath_date': '2021-05-10T00:13:57.214Z',
  'atl': 0.148183,
  'atl_change_percentage': 6123.04304,
  'atl_date': '2017-11-29T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-04-28T07:17:25.805Z'},
 {'id': 'canton-network',
  'symbol': 'cc',
  'name': 'Canton',
  'image': 'https://coin-images.coingecko.com/coins/images/70468/large/Canton-Ticker_%281%29.png?1762826299',
  'current_price': 0.149453,
  'market_cap': 5738396359,
  'market_cap_rank': 19,
  'fully_diluted_valuation': 5738396359,
  'total_volume': 7082097,
  'high_24h': 0.149882,
  'low_24h': 0.1473,
  'price_change_24h': -0.000429368353983578,
  'price_change_percentage_24h': -0.28647,
  'market_cap_change_24h': -19958604.446343422,
  'market_cap_change_percentage_24h': -0.3466,
  'circulating_supply': 38405853287.48317,
  'total_supply': 38405853287.48317,
  'max_supply': None,
  'ath': 0.194152,
  'ath_change_percentage': -23.14904,
  'ath_date': '2026-02-03T08:02:08.411Z',
  'atl': 0.059024,
  'atl_change_percentage': 152.79086,
  'atl_date': '2025-12-06T10:32:09.784Z',
  'roi': None,
  'last_updated': '2026-04-28T07:17:25.223Z'},
 {'id': 'zcash',
  'symbol': 'zec',
  'name': 'Zcash',
  'image': 'https://coin-images.coingecko.com/coins/images/486/large/circle-zcash-color.png?1696501740',
  'current_price': 335.9,
  'market_cap': 5606135665,
  'market_cap_rank': 20,
  'fully_diluted_valuation': 5606552081,
  'total_volume': 509455788,
  'high_24h': 360.7,
  'low_24h': 335.93,
  'price_change_24h': -19.200160757643346,
  'price_change_percentage_24h': -5.40696,
  'market_cap_change_24h': -313425524.03119946,
  'market_cap_change_percentage_24h': -5.29474,
  'circulating_supply': 16681307.9780448,
  'total_supply': 16682547.0405448,
  'max_supply': 21000000.0,
  'ath': 3191.93,
  'ath_change_percentage': -89.47656,
  'ath_date': '2016-10-29T00:00:00.000Z',
  'atl': 16.08,
  'atl_change_percentage': 1988.91881,
  'atl_date': '2024-07-05T04:22:29.321Z',
  'roi': None,
  'last_updated': '2026-04-28T07:17:23.703Z'},
 {'id': 'stellar',
  'symbol': 'xlm',
  'name': 'Stellar',
  'image': 'https://coin-images.coingecko.com/coins/images/100/large/fmpFRHHQ_400x400.jpg?1735231350',
  'current_price': 0.164469,
  'market_cap': 5478695797,
  'market_cap_rank': 21,
  'fully_diluted_valuation': 8227741254,
  'total_volume': 100176289,
  'high_24h': 0.168862,
  'low_24h': 0.164473,
  'price_change_24h': -0.003933138208635389,
  'price_change_percentage_24h': -2.33556,
  'market_cap_change_24h': -131473124.71771526,
  'market_cap_change_percentage_24h': -2.34348,
  'circulating_supply': 33295235117.98411,
  'total_supply': 50001786868.73495,
  'max_supply': None,
  'ath': 0.875563,
  'ath_change_percentage': -81.18542,
  'ath_date': '2018-01-03T00:00:00.000Z',
  'atl': 0.00047612,
  'atl_change_percentage': 34498.91226,
  'atl_date': '2015-03-05T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-04-28T07:17:20.719Z'},
 {'id': 'memecore',
  'symbol': 'm',
  'name': 'MemeCore',
  'image': 'https://coin-images.coingecko.com/coins/images/53247/large/square-bg-transparent.png?1752637478',
  'current_price': 3.55,
  'market_cap': 4609061196,
  'market_cap_rank': 22,
  'fully_diluted_valuation': 19082801501,
  'total_volume': 16105670,
  'high_24h': 4.22,
  'low_24h': 3.55,
  'price_change_24h': -0.6668009313837171,
  'price_change_percentage_24h': -15.80176,
  'market_cap_change_24h': -830235154.0312452,
  'market_cap_change_percentage_24h': -15.26365,
  'circulating_supply': 1295203620.143494,
  'total_supply': 5362504972.986989,
  'max_supply': 10000000000.0,
  'ath': 4.82,
  'ath_change_percentage': -26.27547,
  'ath_date': '2026-04-24T01:10:07.284Z',
  'atl': 0.04746135,
  'atl_change_percentage': 7383.8503,
  'atl_date': '2025-07-04T03:56:17.448Z',
  'roi': None,
  'last_updated': '2026-04-28T07:17:23.683Z'},
 {'id': 'usd1-wlfi',
  'symbol': 'usd1',
  'name': 'USD1',

In [4]:
df = pd.DataFrame(response.json())

In [5]:
df.head()

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,76507.000000,1533277467419,1,1533277467419,3.328534e+10,78226.00,...,2.002179e+07,2.100000e+07,126080.00,-39.31837,2025-10-06T18:57:42.558Z,67.810000,1.127277e+05,2013-07-06T00:00:00.000Z,None,2026-04-28T07:17:21.934Z
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,2272.820000,274506054614,2,274506054614,1.449207e+10,2327.90,...,1.206883e+08,NaN,4946.05,-54.04781,2025-08-24T19:21:03.333Z,0.432979,5.248258e+05,2015-10-20T00:00:00.000Z,"{'times': 38.719633322207436, 'currency': 'btc...",2026-04-28T07:17:22.269Z
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,0.999885,189712695305,3,195179052274,5.712857e+10,1.00,...,1.951999e+11,NaN,1.32,-24.42851,2018-07-24T00:00:00.000Z,0.572521,7.464562e+01,2015-03-02T00:00:00.000Z,None,2026-04-28T07:17:22.834Z
3,ripple,xrp,XRP,https://coin-images.coingecko.com/coins/images...,1.390000,85599699229,4,138749315633,1.838960e+09,1.42,...,9.998567e+10,1.000000e+11,3.65,-61.99215,2025-07-18T03:40:53.808Z,0.002686,5.149357e+04,2014-05-22T00:00:00.000Z,None,2026-04-28T07:17:23.622Z
4,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,622.350000,83931297076,5,83931297076,8.680152e+08,628.80,...,1.347862e+08,2.000000e+08,1369.99,-54.57279,2025-10-13T08:41:24.131Z,0.039818,1.562896e+06,2017-10-19T00:00:00.000Z,None,2026-04-28T07:17:25.866Z

In [6]:
df = df[['id','name','current_price','market_cap','total_volume','max_supply','price_change_percentage_24h','circulating_supply']]

In [7]:
df

,id,name,current_price,market_cap,total_volume,max_supply,price_change_percentage_24h,circulating_supply
0,bitcoin,Bitcoin,76507.000000,1533277467419,3.328534e+10,2.100000e+07,-1.40934,2.002179e+07
1,ethereum,Ethereum,2272.820000,274506054614,1.449207e+10,NaN,-1.91983,1.206883e+08
2,tether,Tether,0.999885,189712695305,5.712857e+10,NaN,-0.01997,1.897329e+11
3,ripple,XRP,1.390000,85599699229,1.838960e+09,1.000000e+11,-2.15565,6.168494e+10
4,binancecoin,BNB,622.350000,83931297076,8.680152e+08,2.000000e+08,-0.57157,1.347862e+08
...,...,...,...,...,...,...,...,...
95,official-trump,Official Trump,2.500000,582063118,1.273974e+08,1.000000e+09,-1.63565,2.324988e+08
96,midnight-3,Midnight,0.033682,559939892,1.989589e+07,2.400000e+10,-6.67605,1.660740e+10
97,usual-usd,Usual USD,0.998019,556532744,1.273630e+05,NaN,-0.01283,5.576372e+08
98,bonk,Bonk,0.000006,543010706,3.610991e+07,8.799528e+13,-0.56931,8.799474e+13
99,ylds,YLDS,0.999827,539089929,1.112167e+07,NaN,-0.01723,5.391522e+08

In [8]:
import requests
import pandas as pd
import time

df_list = []

for i in range(1, 50):
    print(f"Fetching page {i}...")

    url = f"https://api.coingecko.com/api/v3/coins/markets" \
          f"?vs_currency=usd&order=market_cap_desc&per_page=100&page={i}"

    response = requests.get(url)
    data = response.json()

    if not isinstance(data, list):
        print("API returned error:", data)
        break

    if len(data) == 0:
        print("No more data. Stopping.")
        break

    
    temp_df = pd.DataFrame(data, columns=[
        'id','name','current_price','market_cap','total_volume',
        'max_supply','price_change_percentage_24h','circulating_supply'
    ])

    df_list.append(temp_df)
    time.sleep(1)  

df = pd.concat(df_list, ignore_index=True)

df.head()

Fetching page 1...
Fetching page 2...
Fetching page 3...
Fetching page 4...
Fetching page 5...
API returned error: {'status': {'error_code': 429, 'error_message': "You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}

,id,name,current_price,market_cap,total_volume,max_supply,price_change_percentage_24h,circulating_supply
0,bitcoin,Bitcoin,76507.000000,1533277467419,3.328534e+10,2.100000e+07,-1.40934,2.002179e+07
1,ethereum,Ethereum,2272.820000,274506054614,1.449207e+10,NaN,-1.91983,1.206883e+08
2,tether,Tether,0.999885,189712695305,5.712857e+10,NaN,-0.01997,1.897329e+11
3,ripple,XRP,1.390000,85599699229,1.838960e+09,1.000000e+11,-2.15565,6.168494e+10
4,binancecoin,BNB,622.350000,83931297076,8.680152e+08,2.000000e+08,-0.57157,1.347862e+08

In [9]:
df.shape

(400, 8)

In [10]:
df.to_csv("Crypto.csv")